name: First github actions workflow
on:
  push:  # enabling push event on master branch to fire the workflow
  
jobs:
  job1:
    runs-on: window-latest
    steps:
      - name: checkout the current code using public action
        uses: actions/checkout@v2
      - name: get the list of files in our current directory and its subdirectories
        run: # this | enables us to multiple commands, good for formatting
          pwd
          ld - alR
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: print current files 
        run: |
          pwd
          ls -alR
          
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: print env variables
        run: echo $VAR1 $VAR2 $VAR3
        env:
          VAR1: Thank you
          VAR2: Very Much
          VAR3: Enjoy Vinay !!!!
       
